version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - 8082:8080
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: expensetracker
      MYSQL_USER: cretu
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password



